import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRoundCamera} from '../src/round-camera.js';
const track=(kind,facing)=>({kind,stopped:false,stop(){this.stopped=true},getSettings(){return {facingMode:facing}}});
const stream=tracks=>({getTracks:()=>tracks,getVideoTracks:()=>tracks.filter(t=>t.kind==='video'),getAudioTracks:()=>tracks.filter(t=>t.kind==='audio')});
function setup(getUserMedia){const microphone=track('audio'),front=track('video','user'),canvasTrack=track('video'),initial=stream([front,microphone]);let cleared=false;return {microphone,front,canvasTrack,initial,get cleared(){return cleared},deps:{media:{getUserMedia},makeVideo:()=>({readyState:2,videoWidth:640,videoHeight:480,play:async()=>{},pause(){}}),makeCanvas:()=>({getContext:()=>({drawImage(){}}),captureStream:()=>stream([canvasTrack])}),makeStream:stream,schedule:()=>1,unschedule:()=>{cleared=true}}}}
test('front/back switch keeps one video track and continuous microphone',async()=>{const created=[];const s=setup(async constraints=>{assert.equal(constraints.audio,false);const t=track('video',constraints.video.facingMode.exact);created.push(t);return stream([t])});const c=await createRoundCamera(s.initial,s.deps);const stable=c.stream.getVideoTracks()[0];assert.equal(c.facing,'user');await c.flip();assert.equal(c.facing,'environment');assert.equal(c.stream.getVideoTracks()[0],stable);assert.equal(s.microphone.stopped,false);assert.equal(s.front.stopped,true);await c.flip();assert.equal(c.facing,'user');assert.equal(created[0].stopped,true);assert.equal(s.microphone.stopped,false);c.close();assert.equal(created[1].stopped,true);assert.equal(s.microphone.stopped,true);assert.equal(stable.stopped,true);assert.equal(s.cleared,true)});
test('missing rear camera restores front camera without ending the recording',async()=>{const s=setup(async c=>{if(c.video.facingMode.exact)throw Error('No rear camera');return stream([track('video','user')])});const c=await createRoundCamera(s.initial,s.deps);await assert.rejects(c.flip(),/Вторая камера недоступна/);assert.equal(c.facing,'user');assert.equal(s.microphone.stopped,false);assert.equal(s.canvasTrack.stopped,false);c.close()});
test('closing during camera acquisition releases late-arriving tracks',async()=>{let resolve;const s=setup(()=>new Promise(r=>resolve=r));const c=await createRoundCamera(s.initial,s.deps);const flip=c.flip();assert.equal(await c.flip(),false);c.close();const late=track('video','environment');resolve(stream([late]));assert.equal(await flip,false);assert.equal(late.stopped,true);assert.equal(s.microphone.stopped,true)});
