let me=null,people=[],active=null,filter='all',messages=[],hasMore=false,pollBusy=false,sending=false,round=false,recorder=null,recordStream=null,recordChat=null,recordChunks=[],drafts={};
const colors=['#d1fa70','#85d5ff','#d0b4ff','#ffbda2','#8ce4ca'];
const initials=n=>n.split(' ').map(x=>x[0]||'').slice(0,2).join('').toUpperCase();
const fileUrl=id=>'/api/files/'+encodeURIComponent(id);
const avatarHTML=(name,id)=>id?`<img src="${fileUrl(id)}" alt="${esc(name)}">`:esc(initials(name));
const chatName=p=>p.kind==='group'?p.title:p.peer_name||'Переписка';
const formatTime=t=>new Date(t).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'});
const kindLabel=k=>({image:'Фотография',video:'Видео',round:'Видеокружок',audio:'Голосовое сообщение',file:'Файл'}[k]||'');
let light=false;try{light=localStorage.getItem('ryadom-light')==='true'}catch{}document.body.classList.toggle('light',light);
function apply(){document.documentElement.style.setProperty('--accent',me?.accent||'#d1fa70');if(me)$('#myAvatar').innerHTML=avatarHTML(me.name,me.avatar)}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').hidden=true,5000)}
async function api(path,options={}){const o={credentials:'same-origin',...options};if(o.body&&!(o.body instanceof FormData)){o.headers={'content-type':'application/json',...o.headers};o.body=JSON.stringify(o.body)}let r;try{r=await fetch('/api'+path,o)}catch{throw Error('Нет связи. Проверь интернет и попробуй ещё раз.')}const d=await r.json().catch(()=>({error:'Сервис временно недоступен'}));if(!r.ok){if(r.status===401&&me){me=null;showAuth('login');$('#app').hidden=true;$('#modal').close()}throw Error(d.error||'Не удалось выполнить запрос')}return d}
function showAuth(mode='login'){$('#auth').hidden=false;const recovery=mode==='recover',register=mode==='register';$('#authForm').innerHTML=`<div class="logo" style="margin-bottom:25px">${icon('logo')}</div><div class="label">ТВОИ ЛЮДИ. ТВОЁ ПРОСТРАНСТВО.</div><h1>${register?'Давай знакомиться':recovery?'Вернуться к своим':'Снова рядом<span style="color:var(--accent)">.</span>'}</h1><p class="authsub">${register?'Создай аккаунт и позови друзей.':recovery?'Введи код, сохранённый при регистрации.':'Войди по нику и паролю.'}</p>${register?'<label class="field" for="authName">Как тебя зовут</label><input class="fieldinput" id="authName" autocomplete="name" maxlength="40" required>':''}<label class="field" for="authHandle">Твой ник</label><input class="fieldinput" id="authHandle" autocomplete="username" placeholder="например, sasha" pattern="@?[A-Za-z0-9_]{3,24}" minlength="3" maxlength="25" autocapitalize="none" spellcheck="false" required>${register?'<div class="hint" style="text-align:left">3–24 латинские буквы, цифры или _</div>':''}${recovery?'<label class="field" for="recoveryInput">Код восстановления</label><input class="fieldinput" id="recoveryInput" autocomplete="off" required>':''}<label class="field" for="authPassword">${recovery?'Новый пароль':'Пароль'}</label><input class="fieldinput" id="authPassword" type="password" minlength="10" maxlength="128" autocomplete="${register||recovery?'new-password':'current-password'}" required>${register||recovery?'<div class="hint" style="text-align:left">Не менее 10 символов</div>':''}<div id="authError" role="alert" class="formerror"></div><button class="primary" id="authSubmit">${register?'Создать аккаунт':recovery?'Восстановить доступ':'Войти'}</button><div class="authlinks"><button type="button" id="switchAuth">${register||recovery?'Уже есть аккаунт? Войти':'Впервые здесь? Зарегистрироваться'}</button>${!register&&!recovery?'<button type="button" id="forgot">Не помню пароль</button>':''}</div><div class="hint">Без входа через ChatGPT</div>`;$('#switchAuth').onclick=()=>showAuth(register||recovery?'login':'register');if($('#forgot'))$('#forgot').onclick=()=>showAuth('recover');$('#authForm').onsubmit=async e=>{e.preventDefault();const b={handle:$('#authHandle').value,password:$('#authPassword').value};if(register)b.name=$('#authName').value;if(recovery)b.recovery=$('#recoveryInput').value;$('#authSubmit').disabled=true;$('#authSubmit').textContent='Подожди…';$('#authError').textContent='';try{const d=await api('/'+mode,{method:'POST',body:b});me=d.user;await enter();if(d.recovery)showRecovery(d.recovery)}catch(e){$('#authError').textContent=e.message;$('#authSubmit').disabled=false;$('#authSubmit').textContent=register?'Создать аккаунт':recovery?'Восстановить доступ':'Войти'}}}
function showRecovery(code){modal(`<div class="modalbody"><h2>Сохрани доступ</h2><p>Это твой код восстановления. Он нужен, если забудешь пароль. Не отправляй его другим людям.</p><textarea readonly class="fieldinput" style="min-height:100px;overflow-wrap:anywhere" aria-label="Код восстановления">${esc(code)}</textarea><button class="primary" id="downloadRecovery">Скачать код</button><button class="primary" data-close style="background:var(--card);color:var(--text)">Я сохранил код</button></div>`);$('#downloadRecovery').onclick=()=>{const blob=new Blob([`Рядом\nНик: ${me.handle}\nКод восстановления: ${code}\nХрани этот файл в безопасном месте.`],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ryadom-recovery.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
async function enter(){$('#auth').hidden=true;$('#app').hidden=false;$('#authForm').innerHTML='';active=null;messages=[];people=[];drafts={};$('#message').value='';$('#app').classList.remove('inchat');apply();emptyChat();await refreshChats();$('#connection').textContent='На связи';}
function emptyChat(){$('#peerName').textContent='Твои люди — рядом';$('#peerStatus').textContent='Начни с поиска друга';$('#peerAvatar').innerHTML=icon('chat');$('#messages').innerHTML='<div class="welcome"><div class="logo">'+icon('chat')+'</div><h2>Здесь начнётся ваша история</h2><p>Найди друга по нику и напиши первым.</p><button class="primary" id="welcomeFind">Найти друга</button></div>';$('#welcomeFind').onclick=findPeople;$('.composerwrap').hidden=true}
function list(){const q=$('#search').value.toLowerCase();const found=people.filter(p=>(filter==='all'||p.kind===filter)&&chatName(p).toLowerCase().includes(q));$('#chats').innerHTML=found.map(p=>`<button class="chat ${p.id===active?'active':''}" data-id="${p.id}"><span class="avatar">${avatarHTML(chatName(p),p.peer_avatar)}</span><span class="chatbody"><span class="chatline"><span class="chatname">${esc(chatName(p))}</span><span class="time">${formatTime(p.updated)}</span></span><span class="preview">${esc(p.last||kindLabel(p.last_kind)||'Начните общение')}</span></span></button>`).join('')||`<div class="empty">${q?'Ничего не найдено':'Пока тихо. Позови своих.'}<button class="primary" id="emptyFind">Найти друга</button></div>`;$('#chats').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>select(b.dataset.id));if($('#emptyFind'))$('#emptyFind').onclick=findPeople}
async function refreshChats(){const d=await api('/chats');people=d.chats;list()}
function render(force=false){const p=people.find(p=>p.id===active);if(!p)return;$('#peerName').textContent=chatName(p);$('#peerAvatar').innerHTML=avatarHTML(chatName(p),p.peer_avatar);$('#peerStatus').textContent=p.kind==='group'?p.member_count+' участников':'@'+p.peer_handle;$('.composerwrap').hidden=false;const pane=$('#messages'),nearBottom=pane.scrollHeight-pane.scrollTop-pane.clientHeight<140;let date='';pane.innerHTML=(hasMore?'<button id="older" class="tab">Загрузить более ранние</button>':'')+(messages.length?messages.map(m=>{const day=new Date(m.created).toLocaleDateString('ru',{day:'numeric',month:'long'}),divider=date===day?'':`<div class="day">${day}</div>`;date=day;const url=m.file_id?fileUrl(m.file_id):'';return divider+`<div class="bubble ${m.sender===me.id?'mine':''}">${p.kind==='group'&&m.sender!==me.id?`<div class="sender">${esc(m.sender_name)}</div>`:''}${m.kind==='image'?`<a href="${url}" target="_blank" rel="noopener"><img loading="lazy" src="${url}" alt="${esc(m.file_name)}"></a>`:m.kind==='video'||m.kind==='round'?`<video ${m.kind==='round'?'class="round"':''} controls playsinline preload="metadata" src="${url}"></video>`:m.kind==='audio'?`<audio controls preload="metadata" src="${url}"></audio>`:m.kind==='file'?`<a class="file" href="${url}" download>${icon('file')}<div>${esc(m.file_name)}<span>${(m.file_size/1024/1024).toFixed(1)} МБ · скачать</span></div></a>`:esc(m.body).replace(/\n/g,'<br>')}<small>${formatTime(m.created)}${m.sender===me.id?' · отправлено':''}</small></div>`}).join(''):'<div class="empty">Скажи «привет» 👋</div>');if(force||nearBottom)pane.scrollTop=pane.scrollHeight;if($('#older'))$('#older').onclick=async()=>{const id=active,oldHeight=pane.scrollHeight;try{const d=await api('/messages?chat='+encodeURIComponent(id)+'&before='+messages[0].created);if(active!==id)return;messages=[...d.messages,...messages];hasMore=d.hasMore;render();pane.scrollTop=pane.scrollHeight-oldHeight}catch(e){toast(e.message)}}}
async function select(id){if(active)drafts[active]=$('#message').value;active=id;$('#message').value=drafts[id]||'';$('#app').classList.add('inchat');$('#attachments').hidden=true;list();$('#messages').innerHTML='<div class="empty">Загружаем переписку…</div>';try{const d=await api('/messages?chat='+encodeURIComponent(id));if(active!==id)return;messages=d.messages;hasMore=d.hasMore;render(true)}catch(e){if(active===id)$('#messages').innerHTML='<div class="empty">'+esc(e.message)+'<button id="retryChat" class="primary">Повторить</button></div>';if($('#retryChat'))$('#retryChat').onclick=()=>select(id)}}
async function refreshMessages(){if(!active)return;const id=active,d=await api('/messages?chat='+encodeURIComponent(id));if(active!==id)return;const last=messages.at(-1);if(last?.id===d.messages.at(-1)?.id&&messages.length)return;const old=messages.filter(m=>m.created<(d.messages[0]?.created||0));messages=[...old,...d.messages];hasMore=old.length?hasMore:d.hasMore;render()}
async function send(){const text=$('#message').value.trim(),chat=active;if(!text||!chat||sending)return;sending=true;$('#send').disabled=true;try{await api('/messages',{method:'POST',body:{chat,text,nonce:crypto.randomUUID()}});if(active===chat&&$('#message').value.trim()===text)$('#message').value='';drafts[chat]='';await refreshMessages();await refreshChats()}catch(e){toast(e.message)}finally{sending=false;$('#send').disabled=false}}
$('#send').onclick=send;$('#message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('#message').oninput=()=>{if(active)drafts[active]=$('#message').value};$('#back').onclick=()=>$('#app').classList.remove('inchat');$('#navChats').onclick=()=>{$('#app').classList.remove('inchat');list()};$('#search').oninput=list;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));list()});
function modal(html){$('#modal').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();$('#modal').querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#modal').close())}const close=`<button class="iconbtn close" data-close aria-label="Закрыть">${icon('close')}</button>`;$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close()};
function findPeople(){modal(`<div class="cover" style="height:65px;background:var(--card)">${close}</div><div class="modalbody"><h2>Найти своих</h2><p>Твой ник: <strong>@${esc(me.handle)}</strong>. Отправь другу ник и ссылку на этот сайт.</p><input class="fieldinput" id="findHandle" placeholder="Ник друга — минимум 2 символа" autocapitalize="none" aria-label="Ник друга"><div id="foundPeople" style="margin-top:15px"></div><button class="primary" id="newGroup" style="background:var(--card);color:var(--text)">Создать группу</button></div>`);let timer;$('#findHandle').oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const input=$('#findHandle');if(!input)return;const q=input.value;try{const d=await api('/users?q='+encodeURIComponent(q));if(!$('#findHandle')||$('#findHandle').value!==q)return;$('#foundPeople').innerHTML=d.users.map(u=>`<button class="chat" data-user="${esc(u.handle)}"><span class="avatar">${avatarHTML(u.name,u.avatar)}</span><span>${esc(u.name)}<span class="preview" style="display:block">@${esc(u.handle)}</span></span></button>`).join('')||'<div class="empty">'+(q.length<2?'Введи минимум 2 символа':'Пользователь не найден. Возможно, друг ещё не зарегистрировался.')+'</div>';document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const d=await api('/chats',{method:'POST',body:{handle:b.dataset.user}});await refreshChats();$('#modal').close();await select(d.chatId)}catch(e){toast(e.message);b.disabled=false}})}catch(e){toast(e.message)}},350)};$('#newGroup').onclick=()=>{modal(`<div class="modalbody"><h2>Своя компания</h2><label class="field" for="groupName">Название группы</label><input class="fieldinput" id="groupName" maxlength="60"><label class="field" for="groupHandles">Ники друзей через запятую</label><input class="fieldinput" id="groupHandles" placeholder="sasha, anya, max"><p>Добавь только тех, с кем хочешь общаться.</p><div class="formerror" id="groupError"></div><button class="primary" id="createGroup">Создать группу</button><button class="primary" data-close style="background:var(--card);color:var(--text)">Отмена</button></div>`);$('#createGroup').onclick=async()=>{$('#createGroup').disabled=true;try{const d=await api('/chats',{method:'POST',body:{kind:'group',title:$('#groupName').value,handles:$('#groupHandles').value.split(',').map(x=>x.trim()).filter(Boolean)}});await refreshChats();$('#modal').close();await select(d.chatId)}catch(e){$('#groupError').textContent=e.message;$('#createGroup').disabled=false}}}}
$('#navContacts').onclick=findPeople;$('#newChat').onclick=findPeople;
async function profile(own=false){if(!own&&!active)return;try{const users=own?[me]:(await api('/chat-profile?chat='+encodeURIComponent(active))).users,p=own?me:users.find(u=>u.id!==me.id)||me;modal(`<div class="cover" style="background:linear-gradient(120deg,#394c3b,${esc(p.accent)})">${close}</div><div class="modalbody"><div class="avatar profileavatar">${avatarHTML(p.name,p.avatar)}</div><h2>${esc(p.name)}</h2><p>@${esc(p.handle)}</p>${own?`<button id="changeAvatar" style="color:var(--accent)">Изменить фото</button><label class="field" for="profileName">Имя</label><input id="profileName" class="fieldinput" maxlength="40" value="${esc(me.name)}"><label class="field" for="profileBio">О себе</label><textarea id="profileBio" class="fieldinput" maxlength="180">${esc(me.bio)}</textarea><button class="primary" id="saveProfile">Сохранить</button><button class="primary" id="logout" style="background:var(--card);color:var(--text)">Выйти из аккаунта</button>`:`<p>${esc(p.bio)||'Пока ничего о себе'}</p>${users.length>2?'<div class="field">Участники</div>'+users.map(u=>`<p>${esc(u.name)} · @${esc(u.handle)}</p>`).join(''):''}<button class="primary" data-close>К переписке</button>`}</div>`);if(own){$('#changeAvatar').onclick=()=>$('#avatarUpload').click();$('#saveProfile').onclick=async()=>{const button=$('#saveProfile');button.disabled=true;try{const d=await api('/profile',{method:'PATCH',body:{name:$('#profileName').value,bio:$('#profileBio').value,accent:me.accent}});me=d.user;apply();$('#modal').close();toast('Профиль сохранён')}catch(e){toast(e.message);button.disabled=false}};$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST',body:{}});cancelRecording();me=null;active=null;messages=[];people=[];$('#modal').close();$('#app').hidden=true;showAuth()}catch(e){toast(e.message)}}}}catch(e){toast(e.message)}}
$('#navProfile').onclick=()=>profile(true);$('#peerInfo').onclick=$('#details').onclick=()=>profile();
async function uploadFile(f,kind='',chat=active){if(!f)return;if(kind!=='avatar'&&!chat)throw Error('Сначала выбери чат');if(f.size>(kind==='avatar'?2:20)*1024*1024)throw Error(kind==='avatar'?'Фото должно быть до 2 МБ':'Выбери файл до 20 МБ');const form=new FormData();form.append('file',f);form.append('kind',kind);if(chat)form.append('chat',chat);$('#hint').textContent='Загружаем файл…';try{const d=await api('/upload',{method:'POST',body:form});if(kind==='avatar'){me.avatar=d.fileId;apply();await profile(true)}else{await refreshChats();await refreshMessages()}}finally{$('#hint').textContent='Фото, видео и файлы до 20 МБ · 250 МБ на аккаунт'}}
$('#avatarUpload').onchange=async e=>{try{await uploadFile(e.target.files[0],'avatar');e.target.value=''}catch(e){toast(e.message)}};$('#upload').onchange=async e=>{try{await uploadFile(e.target.files[0],round?'round':'');e.target.value=''}catch(e){toast(e.message)}};
$('#attach').onclick=()=>$('#attachments').hidden=!$('#attachments').hidden;$('#emoji').onclick=()=>{$('#message').value+=' ✨';$('#message').focus()};document.querySelectorAll('[data-upload]').forEach(b=>b.onclick=()=>{round=!!b.dataset.round;$('#upload').accept=b.dataset.upload;$('#upload').click();$('#attachments').hidden=true});
let roundCamera=null,startingRecord=false;
function stopRecordingResources(){roundCamera?.close();roundCamera=null;recordStream?.getTracks().forEach(t=>t.stop());clearTimeout(window.recTimeout);clearInterval(window.recInterval)}
function cancelRecording(){if(recorder?.state==='recording'){recorder.onstop=()=>{};recorder.stop()}stopRecordingResources();$('#record').style.color='';$('#hint').textContent='Фото, видео и файлы до 20 МБ · 250 МБ на аккаунт'}
async function record(roundMode=false){
  if(startingRecord)return;
  if(recorder?.state==='recording'){recorder.stop();return}
  if(!active)return;
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Запись недоступна в этом браузере. Прикрепи готовый файл.');return}
  startingRecord=true;const chat=active;
  try{
    recordStream=await navigator.mediaDevices.getUserMedia(roundMode?{audio:true,video:{facingMode:{ideal:'user'},width:{ideal:480},height:{ideal:480}}}:{audio:true});
    if(!me){stopRecordingResources();return}
    if(roundMode)roundCamera=await createRoundCamera(recordStream);
    recordChat=chat;recordChunks=[];
    recorder=new MediaRecorder(roundMode?roundCamera.stream:recordStream);
    recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};
    let elapsed=0;
    if(roundMode){
      modal(`<div class="modalbody"><h2>Твой кружок</h2><video id="cameraPreview" autoplay muted playsinline style="width:100%;aspect-ratio:1;object-fit:cover;border-radius:50%;margin-top:20px"></video><div class="row" style="justify-content:space-between"><p id="recordTime">0:00 / 1:00</p><button id="flipCamera" class="camera-switch" aria-label="Переключить переднюю и заднюю камеру"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h3l2-3h6l2 3h3v13H4zM8 11a4 4 0 0 1 7-1l1 2M16 9v3h-3M16 16a4 4 0 0 1-7 1l-1-2M8 18v-3h3"/></svg><span>Повернуть</span></button></div><p id="cameraStatus" class="hint" aria-live="polite">Передняя камера</p><button class="primary" id="stopRound">Закончить запись</button><button id="cancelRound" class="tab" style="width:100%;margin-top:10px">Отмена</button></div>`);
      $('#cameraPreview').srcObject=roundCamera.stream;
      $('#cameraPreview').play().catch(()=>{});
      $('#stopRound').onclick=()=>{if(recorder.state==='recording')recorder.stop()};
      $('#cancelRound').onclick=()=>{cancelRecording();$('#modal').close()};
      $('#flipCamera').onclick=async()=>{
        const camera=roundCamera,button=$('#flipCamera');if(!camera)return;button.disabled=true;
        $('#cameraStatus').textContent='Переключаем камеру…';
        try{await camera.flip();if(camera===roundCamera&&$('#cameraStatus'))$('#cameraStatus').textContent=camera.facing==='user'?'Передняя камера':'Задняя камера'}
        catch(e){if(camera===roundCamera&&$('#cameraStatus'))$('#cameraStatus').textContent=e.message}
        finally{if(camera===roundCamera&&$('#flipCamera'))$('#flipCamera').disabled=false}
      };
    }else{$('#record').style.color='#ff8989';$('#hint').textContent='Идёт запись. Нажми микрофон, чтобы закончить.'}
    recorder.onstop=()=>{
      const mime=recorder.mimeType,blob=new Blob(recordChunks,{type:mime}),extension=mime.includes('mp4')?'mp4':'webm',f=new File([blob],(roundMode?'circle.':'voice.')+extension,{type:mime});
      stopRecordingResources();$('#record').style.color='';$('#hint').textContent='Фото, видео и файлы до 20 МБ · 250 МБ на аккаунт';
      if(!blob.size){toast('Запись не получилась. Попробуй ещё раз.');return}
      const url=URL.createObjectURL(blob);
      modal(`<div class="modalbody"><h2>${roundMode?'Отправить кружок?':'Отправить голосовое?'}</h2>${roundMode?`<video controls playsinline src="${url}" style="width:100%;aspect-ratio:1;object-fit:cover;border-radius:50%;margin-top:20px"></video>`:`<audio controls src="${url}" style="width:100%;margin-top:25px"></audio>`}<div class="formerror" id="recordError"></div><button class="primary" id="sendRecord">Отправить</button><button class="primary" data-close style="background:var(--card);color:var(--text)">Отмена</button></div>`);
      $('#modal').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});
      $('#sendRecord').onclick=async()=>{const b=$('#sendRecord');b.disabled=true;try{await uploadFile(f,roundMode?'round':'audio',chat);$('#modal').close()}catch(e){if($('#recordError'))$('#recordError').textContent=e.message;b.disabled=false}};
    };
    recorder.onerror=()=>{cancelRecording();$('#modal').close();toast('Не удалось записать видео. Попробуй ещё раз.')};
    recorder.start();
    window.recTimeout=setTimeout(()=>{if(recorder.state==='recording')recorder.stop()},60000);
    window.recInterval=setInterval(()=>{elapsed++;if($('#recordTime'))$('#recordTime').textContent=Math.floor(elapsed/60)+':'+String(elapsed%60).padStart(2,'0')+' / 1:00'},1000);
  }catch(e){cancelRecording();if($('#cameraPreview'))$('#modal').close();toast(e.message?.includes('браузер')?e.message:'Нет доступа к камере или микрофону. Разреши доступ в настройках браузера.')}
  finally{startingRecord=false}
}
$('#record').onclick=()=>record();$('#recordRound').onclick=()=>{$('#attachments').hidden=true;record(true)};
$('#modal').addEventListener('close',()=>{if(roundCamera)cancelRecording()});
$('#navSettings').onclick=()=>{modal(`<div class="cover" style="height:65px;background:var(--card)">${close}</div><div class="modalbody"><h2>По-твоему</h2><p>Сделай «Рядом» своим.</p><div class="field">Цвет акцента</div><div class="swatches">${colors.map(c=>`<button aria-label="Цвет ${c}" class="swatch ${me.accent===c?'selected':''}" data-color="${c}" style="background:${c}"></button>`).join('')}</div><label class="row"><input type="checkbox" id="lightTheme" ${light?'checked':''}>Светлая тема</label><p>Цвет и профиль сохраняются в аккаунте. Тема — на этом устройстве.</p><button class="primary" data-close>Готово</button></div>`);document.querySelectorAll('[data-color]').forEach(b=>b.onclick=async()=>{try{const d=await api('/profile',{method:'PATCH',body:{name:me.name,bio:me.bio,accent:b.dataset.color}});me=d.user;apply();document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('selected',x===b))}catch(e){toast(e.message)}});$('#lightTheme').onchange=e=>{light=e.target.checked;document.body.classList.toggle('light',light);try{localStorage.setItem('ryadom-light',String(light))}catch{}}};
$('#chatSearch').onclick=()=>{if(!active)return;modal(`<div class="modalbody"><h2>Поиск в загруженных сообщениях</h2><input class="fieldinput" id="query" placeholder="Слово или фраза" aria-label="Поиск сообщений" style="margin-top:20px"><div id="results" class="empty">Введи запрос</div><button class="primary" data-close>Закрыть</button></div>`);$('#query').oninput=()=>{const q=$('#query').value.trim().toLowerCase();$('#results').innerHTML=q?(messages.filter(m=>m.body.toLowerCase().includes(q)).map(m=>`<p>${esc(m.body)}</p>`).join('')||'Ничего не найдено'):'Введи запрос'}};
setInterval(async()=>{if(!me||document.hidden||pollBusy||sending)return;pollBusy=true;try{await refreshChats();await refreshMessages();$('#connection').textContent='На связи'}catch(e){$('#connection').textContent='Нет связи · повторяем подключение'}finally{pollBusy=false}},4000);
(async()=>{try{const d=await api('/me');me=d.user;await enter()}catch(e){showAuth();if(!e.message.includes('Войди')&&!e.message.includes('Сессия'))$('#authError').textContent=e.message}})();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_chat',description:'Открывает существующую переписку текущего пользователя. Не отправляет сообщений.',inputSchema:{type:'object',properties:{chatId:{type:'string'}},required:['chatId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async({chatId})=>{if(!me||typeof chatId!=='string'||!people.some(p=>p.id===chatId))throw Error('Переписка недоступна');await select(chatId);return {chatId}}})).catch(()=>{})}catch{}}
