const enc=new TextEncoder(),hex=a=>Array.from(new Uint8Array(a),x=>x.toString(16).padStart(2,'0')).join(''),random=()=>hex(crypto.getRandomValues(new Uint8Array(32))),uid=()=>crypto.randomUUID();
const digest=async s=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
async function passwordHash(password,salt){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},k,256))}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
class Fail extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(s,m)=>{throw new Fail(s,m)},json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const statement=(env,q,...args)=>env.DB.prepare(q).bind(...args),one=(env,q,...a)=>statement(env,q,...a).first(),all=async(env,q,...a)=>(await statement(env,q,...a).all()).results;
const safeUser=u=>({id:u.id,handle:u.handle,name:u.name,bio:u.bio,avatar:u.avatar,accent:u.accent});
const cookie=t=>`ryadom_session=${t}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`;
async function body(r){if(Number(r.headers.get('content-length'))>20000)fail(413,'Слишком большой запрос');if(!r.headers.get('content-type')?.includes('application/json'))fail(415,'Нужен JSON');let text=await r.text();if(text.length>20000)fail(413,'Слишком большой запрос');try{return JSON.parse(text)}catch{fail(400,'Некорректный запрос')}}
function validPassword(s){if(typeof s!=='string'||s.length<10||s.length>128)fail(400,'Пароль должен содержать от 10 до 128 символов')}
function handle(s){if(typeof s!=='string'||!/^@?[a-zA-Z0-9_]{3,24}$/.test(s))fail(400,'Ник: 3–24 латинские буквы, цифры или _');return s.replace(/^@/,'').toLowerCase()}
function short(s,max){if(typeof s!=='string'||s.length>max)fail(400,'Проверь длину текста');return s.trim()}
async function limit(env,key,max,seconds){const now=Date.now(),id=await digest(key);const result=await one(env,'INSERT INTO limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING count',id,now+seconds*1000,now,now);if(result.count>max)fail(429,'Слишком много попыток. Попробуй позже.')}
async function auth(r,env){const raw=(r.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('ryadom_session='))?.slice(15);if(!raw)fail(401,'Войди в аккаунт');const u=await one(env,'SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?',await digest(raw),Date.now());if(!u)fail(401,'Сессия завершилась. Войди снова.');return u}
async function session(env,u){const token=random();await statement(env,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await digest(token),u.id,Date.now()+2592000000).run();return token}
async function member(env,chatId,userId){if(typeof chatId!=='string'||!await one(env,'SELECT id FROM members WHERE chat_id=? AND user_id=?',chatId,userId))fail(403,'Нет доступа к переписке')}
async function chatList(env,u){return all(env,`SELECT c.id,c.kind,c.title,c.created,
 (SELECT u.name FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=c.id AND m.user_id!=? LIMIT 1) peer_name,
 (SELECT u.handle FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=c.id AND m.user_id!=? LIMIT 1) peer_handle,
 (SELECT u.avatar FROM members m JOIN users u ON u.id=m.user_id WHERE m.chat_id=c.id AND m.user_id!=? LIMIT 1) peer_avatar,
 (SELECT body FROM messages WHERE chat_id=c.id ORDER BY created DESC,id DESC LIMIT 1) last,
 (SELECT kind FROM messages WHERE chat_id=c.id ORDER BY created DESC,id DESC LIMIT 1) last_kind,
 COALESCE((SELECT MAX(created) FROM messages WHERE chat_id=c.id),c.created) updated,
 (SELECT COUNT(*) FROM members WHERE chat_id=c.id) member_count
 FROM chats c JOIN members mm ON mm.chat_id=c.id WHERE mm.user_id=? ORDER BY updated DESC`,u.id,u.id,u.id,u.id)}
export function createApp(HTML){return {async fetch(r,env,ctx){try{
const url=new URL(r.url),path=url.pathname,method=r.method;
if(!path.startsWith('/api/')){if(method!=='GET'&&method!=='HEAD')fail(405,'Метод не разрешён');return new Response(method==='HEAD'?null:HTML,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-cache','x-content-type-options':'nosniff','referrer-policy':'same-origin','permissions-policy':'camera=(self), microphone=(self)','content-security-policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"}})}
if(!env.DB||!env.BUCKET)fail(503,'Сервис подключается. Попробуй чуть позже.');
if(!['GET','HEAD'].includes(method)){const origin=r.headers.get('origin');if(!origin||origin!==url.origin)fail(403,'Недопустимый источник запроса');}
const ip=r.headers.get('cf-connecting-ip')||r.headers.get('x-real-ip')||'unknown';
if(path==='/api/register'&&method==='POST'){
await limit(env,'register:'+ip,6,3600);const b=await body(r),h=handle(b.handle),name=short(b.name,40);if(!name)fail(400,'Укажи имя');validPassword(b.password);if(await one(env,'SELECT id FROM users WHERE handle=?',h))fail(409,'Этот ник уже занят');const id=uid(),salt=random(),recovery=random();const hash=await passwordHash(b.password,salt);try{await statement(env,'INSERT INTO users(id,handle,name,salt,password,recovery,created) VALUES(?,?,?,?,?,?,?)',id,h,name,salt,hash,await digest(recovery),Date.now()).run()}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Этот ник уже занят');throw e}const user=await one(env,'SELECT * FROM users WHERE id=?',id),token=await session(env,user);return json({user:safeUser(user),recovery},201,{'set-cookie':cookie(token)});
}
if(path==='/api/login'&&method==='POST'){
await limit(env,'login-ip:'+ip,30,900);const b=await body(r),h=handle(b.handle);await limit(env,'login-user:'+h,12,900);validPassword(b.password);const u=await one(env,'SELECT * FROM users WHERE handle=?',h);const hash=await passwordHash(b.password,u?.salt||'not-a-real-account-salt');if(!u||!equal(hash,u.password))fail(401,'Неверный ник или пароль');const token=await session(env,u);return json({user:safeUser(u)},200,{'set-cookie':cookie(token)});
}
if(path==='/api/recover'&&method==='POST'){
await limit(env,'recover:'+ip,8,3600);const b=await body(r),h=handle(b.handle);validPassword(b.password);const code=short(b.recovery,100),u=await one(env,'SELECT * FROM users WHERE handle=?',h);if(!u||!equal(await digest(code),u.recovery))fail(400,'Неверный ник или код восстановления');const salt=random(),recovery=random();await env.DB.batch([statement(env,'UPDATE users SET salt=?,password=?,recovery=? WHERE id=?',salt,await passwordHash(b.password,salt),await digest(recovery),u.id),statement(env,'DELETE FROM sessions WHERE user_id=?',u.id)]);return json({user:safeUser(u),recovery},200,{'set-cookie':cookie(await session(env,u))});
}
const u=await auth(r,env);
if(path==='/api/me'&&method==='GET')return json({user:safeUser(u)});
if(path==='/api/logout'&&method==='POST'){const t=(r.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('ryadom_session='))?.slice(15);if(t)await statement(env,'DELETE FROM sessions WHERE token=?',await digest(t)).run();return json({ok:true},200,{'set-cookie':'ryadom_session=; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=0'})}
if(path==='/api/profile'&&method==='PATCH'){const b=await body(r),name=short(b.name,40),bio=short(b.bio,180);if(!name)fail(400,'Укажи имя');if(!['#d1fa70','#85d5ff','#d0b4ff','#ffbda2','#8ce4ca'].includes(b.accent))fail(400,'Неизвестный цвет');await statement(env,'UPDATE users SET name=?,bio=?,accent=? WHERE id=?',name,bio,b.accent,u.id).run();return json({user:safeUser({...u,name,bio,accent:b.accent})})}
if(path==='/api/users'&&method==='GET'){await limit(env,'search:'+u.id,80,60);const q=(url.searchParams.get('q')||'').replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_]{2,24}$/.test(q))return json({users:[]});return json({users:await all(env,'SELECT id,handle,name,bio,avatar,accent FROM users WHERE handle LIKE ? ESCAPE \'!\' AND id!=? LIMIT 20',q.replace(/_/g,'!_')+'%',u.id)})}
if(path==='/api/chats'&&method==='GET')return json({chats:await chatList(env,u)});
if(path==='/api/chats'&&method==='POST'){
await limit(env,'chats:'+u.id,30,3600);const b=await body(r);if(b.kind==='group'){const title=short(b.title,60);if(!title||!Array.isArray(b.handles)||b.handles.length<1||b.handles.length>19)fail(400,'Укажи название и от 1 до 19 друзей');const ids=new Set([u.id]);for(const raw of b.handles){const h=handle(raw),p=await one(env,'SELECT id FROM users WHERE handle=?',h);if(!p)fail(404,'Пользователь @'+h+' не найден');ids.add(p.id)}if(ids.size<2)fail(400,'Добавь хотя бы одного друга');const id=uid();await env.DB.batch([statement(env,'INSERT INTO chats(id,kind,title,created) VALUES(?,?,?,?)',id,'group',title,Date.now()),...[...ids].map(userId=>statement(env,'INSERT INTO members(id,chat_id,user_id) VALUES(?,?,?)',uid(),id,userId))]);return json({chatId:id},201)}
const peer=await one(env,'SELECT id FROM users WHERE handle=?',handle(b.handle));if(!peer)fail(404,'Пользователь не найден');if(peer.id===u.id)fail(400,'Выбери другого пользователя');const pair=[u.id,peer.id].sort().join(':'),id=await digest(pair);await env.DB.batch([statement(env,'INSERT OR IGNORE INTO chats(id,kind,pair,created) VALUES(?,?,?,?)',id,'personal',pair,Date.now()),statement(env,'INSERT OR IGNORE INTO members(id,chat_id,user_id) VALUES(?,?,?)',uid(),id,u.id),statement(env,'INSERT OR IGNORE INTO members(id,chat_id,user_id) VALUES(?,?,?)',uid(),id,peer.id)]);return json({chatId:id});
}
if(path==='/api/messages'&&method==='GET'){const chat=url.searchParams.get('chat');await member(env,chat,u.id);const before=Number(url.searchParams.get('before'))||Date.now()+1;const rows=await all(env,`SELECT m.*,u.name sender_name,f.name file_name,f.mime file_mime,f.size file_size FROM messages m JOIN users u ON u.id=m.sender LEFT JOIN files f ON f.id=m.file_id WHERE m.chat_id=? AND m.created<? ORDER BY m.created DESC,m.id DESC LIMIT 100`,chat,before);return json({messages:rows.reverse(),hasMore:rows.length===100})}
if(path==='/api/chat-profile'&&method==='GET'){const chat=url.searchParams.get('chat');await member(env,chat,u.id);return json({users:await all(env,'SELECT u.id,u.name,u.handle,u.bio,u.avatar,u.accent FROM users u JOIN members m ON m.user_id=u.id WHERE m.chat_id=?',chat)})}
if(path==='/api/messages'&&method==='POST'){await limit(env,'send:'+u.id,100,60);const b=await body(r);await member(env,b.chat,u.id);const text=short(b.text,5000),nonce=short(b.nonce,80);if(!text||!nonce)fail(400,'Пустое сообщение');await statement(env,'INSERT OR IGNORE INTO messages(id,chat_id,sender,body,kind,created,nonce) VALUES(?,?,?,?,?,?,?)',uid(),b.chat,u.id,text,'text',Date.now(),nonce).run();return json({ok:true},201)}
if(path==='/api/upload'&&method==='POST'){
await limit(env,'upload:'+u.id,30,3600);if(Number(r.headers.get('content-length'))>21*1024*1024)fail(413,'Файл должен быть до 20 МБ');const form=await r.formData(),f=form.get('file'),isAvatar=form.get('kind')==='avatar',chat=isAvatar?null:form.get('chat');if(!f||typeof f==='string'||!f.size||f.size>(isAvatar?2:20)*1024*1024)fail(413,isAvatar?'Фото должно быть до 2 МБ':'Файл должен быть до 20 МБ');if(!isAvatar)await member(env,chat,u.id);if(isAvatar&&!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type))fail(400,'Для аватара выбери JPG, PNG, WebP или GIF');const usage=await one(env,'SELECT COALESCE(SUM(size),0) total FROM files WHERE owner=?',u.id);if(usage.total+f.size>250*1024*1024)fail(413,'Достигнут лимит 250 МБ на аккаунт');
const id=uid(),name=f.name.slice(0,160)||'Файл',mime=f.type.split(';')[0]||'application/octet-stream',time=Date.now();await env.BUCKET.put(id,f.stream(),{httpMetadata:{contentType:mime}});try{const queries=[statement(env,'INSERT INTO files(id,owner,chat_id,name,mime,size,created) VALUES(?,?,?,?,?,?,?)',id,u.id,chat,name,mime,f.size,time)];if(isAvatar)queries.push(statement(env,'UPDATE users SET avatar=? WHERE id=?',id,u.id));else{const safeImage=['image/jpeg','image/png','image/webp','image/gif'].includes(mime);const kind=safeImage?'image':mime.startsWith('video/')?(form.get('kind')==='round'?'round':'video'):mime.startsWith('audio/')?'audio':'file';queries.push(statement(env,'INSERT INTO messages(id,chat_id,sender,file_id,kind,created,nonce) VALUES(?,?,?,?,?,?,?)',uid(),chat,u.id,id,kind,time,id))}await env.DB.batch(queries)}catch(e){await env.BUCKET.delete(id);throw e}if(isAvatar&&u.avatar){await env.BUCKET.delete(u.avatar);await statement(env,'DELETE FROM files WHERE id=? AND owner=?',u.avatar,u.id).run()}return json({fileId:id},201);
}
if(path.startsWith('/api/files/')&&['GET','HEAD'].includes(method)){
const id=path.slice('/api/files/'.length),f=await one(env,'SELECT * FROM files WHERE id=?',id);if(!f)fail(404,'Файл не найден');if(f.chat_id)await member(env,f.chat_id,u.id);else if(!await one(env,'SELECT id FROM users WHERE avatar=?',id))fail(403,'Нет доступа');
const o=await env.BUCKET.get(id,{range:r.headers});if(!o)fail(404,'Файл недоступен');const inline=['image/jpeg','image/png','image/webp','image/gif','audio/webm','audio/ogg','audio/mpeg','audio/mp4','audio/wav','video/mp4','video/webm','video/quicktime'].includes(f.mime),headers={'content-type':inline?f.mime:'application/octet-stream','x-content-type-options':'nosniff','cache-control':'private, no-store','content-disposition':`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`,'accept-ranges':'bytes'};if(o.range){headers['content-range']=`bytes ${o.range.offset}-${o.range.offset+o.range.length-1}/${o.size}`;headers['content-length']=String(o.range.length)}else headers['content-length']=String(o.size);return new Response(method==='HEAD'?null:o.body,{status:o.range?206:200,headers});
}
fail(404,'Не найдено');
}catch(e){if(e instanceof Fail)return json({error:e.message},e.status);console.error('Request failed',e?.message);return json({error:'Не удалось выполнить запрос. Попробуй ещё раз.'},503)}}}}
